GET http://localhost/pay-support/api/rabs

###
GET http://localhost/payreq-x/api/rabs/get-payreqs

###
POST https://arkasrv2.arka.own:50000/b1s/v1/Login
Content-Type: application/json

{
  "CompanyDB": "SBO_ARKA_TEST_ADDON",
   "UserName": "manager", 
   "Password": "P@ssw0rd"
}

###
GET https://arkasrv2.arka.own:50000/b1s/v1/ProfitCenters?$select=CenterCode,CenterName
