<table>
    <thead>
        <tr>
            <th>account_no</th>
            <th>remarks</th>
            <th>amount_debet</th>
            <th>amount_credit</th>
            <th>payreq_no</th>
        </tr>
    </thead>
    <tbody>
        <tr></tr>
    </tbody>
</table>